spring:
  application:
    name: Spring Taster
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-taster-test?characterEncoding=utf-8&useUnicode=true
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    hibernate:
      DdlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

server:
  port: 8080


